// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sixteen_str

#include "ui.h"


// IMAGE DATA: assets/speech.png
lv_img_dsc_t ui_img_speech_png = {
    .header.always_zero = 0,
    .header.w = 229,
    .header.h = 135,
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
};

void ui_img_speech_png_load()
{
    ui_img_speech_png.data = UI_LOAD_IMAGE("S:assets/ui_img_speech_png.bin", 92745);
    ui_img_speech_png.data_size = 92745;
}
