// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sixteen_str

#include "ui.h"


// IMAGE DATA: assets/frame_sml.png
lv_img_dsc_t ui_img_frame_sml_png = {
    .header.always_zero = 0,
    .header.w = 540,
    .header.h = 355,
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
};

void ui_img_frame_sml_png_load()
{
    ui_img_frame_sml_png.data = UI_LOAD_IMAGE("S:assets/ui_img_frame_sml_png.bin", 575100);
    ui_img_frame_sml_png.data_size = 575100;
}
