// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sixteen_str

#include "ui.h"


// IMAGE DATA: assets/save.png
lv_img_dsc_t ui_img_save_png = {
    .header.always_zero = 0,
    .header.w = 60,
    .header.h = 60,
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
};

void ui_img_save_png_load()
{
    ui_img_save_png.data = UI_LOAD_IMAGE("S:assets/ui_img_save_png.bin", 10800);
    ui_img_save_png.data_size = 10800;
}
