// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sixteen_str

#include "ui.h"


// IMAGE DATA: assets/night.png
lv_img_dsc_t ui_img_night_png = {
    .header.always_zero = 0,
    .header.w = 800,
    .header.h = 567,
    .header.cf = LV_IMG_CF_TRUE_COLOR,
};

void ui_img_night_png_load()
{
    ui_img_night_png.data = UI_LOAD_IMAGE("S:assets/ui_img_night_png.bin", 907200);
    ui_img_night_png.data_size = 907200;
}
