// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sixteen_str

#include "ui.h"


// IMAGE DATA: assets/choice.png
lv_img_dsc_t ui_img_choice_png = {
    .header.always_zero = 0,
    .header.w = 315,
    .header.h = 115,
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
};

void ui_img_choice_png_load()
{
    ui_img_choice_png.data = UI_LOAD_IMAGE("S:assets/ui_img_choice_png.bin", 108675);
    ui_img_choice_png.data_size = 108675;
}
