// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sixteen_str

#ifndef _SIXTEEN_STR_UI_H
#define _SIXTEEN_STR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

#include "ui_img_manager.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"
#include "ui_Screen2.h"
#include "ui_Screen3.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
extern lv_img_dsc_t ui_img_night_png;   // assets/night.png
void ui_img_night_png_load();
extern lv_img_dsc_t ui_img_choice_png;   // assets/choice.png
void ui_img_choice_png_load();
extern lv_img_dsc_t ui_img_arrow_png;   // assets/arrow.png
void ui_img_arrow_png_load();
extern lv_img_dsc_t ui_img_bird_png;   // assets/bird.png
void ui_img_bird_png_load();
extern lv_img_dsc_t ui_img_frame_sml_png;   // assets/frame_sml.png
void ui_img_frame_sml_png_load();
extern lv_img_dsc_t ui_img_question_png;   // assets/question.png
void ui_img_question_png_load();
extern lv_img_dsc_t ui_img_sett_off_png;   // assets/sett_off.png
void ui_img_sett_off_png_load();
extern lv_img_dsc_t ui_img_frame_lrg_png;   // assets/frame_lrg.png
void ui_img_frame_lrg_png_load();
extern lv_img_dsc_t ui_img_sett_on_png;   // assets/sett_on.png
void ui_img_sett_on_png_load();
extern lv_img_dsc_t ui_img_speech_png;   // assets/speech.png
void ui_img_speech_png_load();

extern lv_img_dsc_t ui_img_loading_gif;
void ui_img_loading_gif_load();
void ui_img_loading_gif_stop();

void ui_bird_talk_anim_start();
void ui_bird_talk_anim_stop();



// FONTS
LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_Font2);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
