// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sixteen_str

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Img;
extern lv_obj_t * ui_ContainerQ;
extern lv_obj_t * ui_PanelQ;
extern lv_obj_t * ui_LabelQ;
extern lv_obj_t * ui_ContainerB;
extern void ui_event_choice1(lv_event_t * e);
extern lv_obj_t * ui_choice1;
extern lv_obj_t * ui_LabelCh1;
extern void ui_event_choice2(lv_event_t * e);
extern lv_obj_t * ui_choice2;
extern lv_obj_t * ui_LabelCh2;
extern void ui_event_end(lv_event_t * e);
extern lv_obj_t * ui_end;
extern lv_obj_t * ui_LabelEnd;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Image7;

// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif