// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sixteen_str

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern void ui_event_sett3(lv_event_t * e);
extern lv_obj_t * ui_sett3;
extern lv_obj_t * ui_bird3;
extern lv_obj_t * ui_Panel;
extern lv_obj_t * ui_Paneln;
extern lv_obj_t * ui_Labeln;
extern lv_obj_t * ui_Name;
extern lv_obj_t * ui_speech;
extern lv_obj_t * ui_Labelsp;
extern lv_obj_t * ui_save;
extern lv_obj_t * ui_reload;
extern lv_obj_t * ui_Container1;
extern void ui_event_ButtonReload(lv_event_t * e);
extern lv_obj_t * ui_ButtonReload;
extern lv_obj_t * ui_LabelReload;
extern void ui_event_ButtonSaveN(lv_event_t * e);
extern lv_obj_t * ui_ButtonSaveN;
extern lv_obj_t * ui_LabelSaveN;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

