// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sixteen_str

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Img1;
extern lv_obj_t * ui_ContainerCh;
extern void ui_event_ch1(lv_event_t * e);
extern lv_obj_t * ui_ch1;
extern lv_obj_t * ui_Labelch1;
extern void ui_event_ch2(lv_event_t * e);
extern lv_obj_t * ui_ch2;
extern lv_obj_t * ui_Labelch2;
extern lv_obj_t * ui_arr1;
extern lv_obj_t * ui_arr2;
extern lv_obj_t * ui_bird1;
extern lv_obj_t * ui_frame1;
extern lv_obj_t * ui_que2;
extern lv_obj_t * ui_Labelq2;
extern void ui_event_sett1(lv_event_t * e);
extern lv_obj_t * ui_sett1;
extern void ui_event_end2(lv_event_t * e);
extern lv_obj_t * ui_end2;
extern lv_obj_t * ui_Labelend2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

