// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sixteen_str

#include "ui.h"


// IMAGE DATA: assets/B2.png
lv_img_dsc_t ui_img_b2_png = {
    .header.always_zero = 0,
    .header.w = 450,
    .header.h = 276,
    .header.cf = LV_IMG_CF_TRUE_COLOR,
};

void ui_img_b2_png_load()
{
    ui_img_b2_png.data = UI_LOAD_IMAGE("S:assets/ui_img_b2_png.bin", 248400);
    ui_img_b2_png.data_size = 248400;
}
