// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sixteen_str

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////


void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_disp_set_theme(dispp, NULL);

    ui_img_night_png_load();
    ui_img_choice_png_load();
    ui_img_arrow_png_load();
    ui_img_bird_png_load();
    ui_img_frame_sml_png_load();
    ui_img_question_png_load();
    ui_img_sett_off_png_load();
    ui_img_frame_lrg_png_load();
    ui_img_sett_on_png_load();
    ui_img_speech_png_load();
    ui_img_save_png_load();
    ui_img_reload_png_load();

    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();

    ui_story_start();

    ui_img_loading_gif_load();

    lv_disp_load_scr(ui_Screen2);
}

void ui_destroy(void)
{
    ui_Screen1_screen_destroy();
    ui_Screen2_screen_destroy();
    ui_Screen3_screen_destroy();
}
