// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sixteen_str

#include "ui.h"
#include "ui_events.h"      
#include "builtin_texts.h" 
#include "user_name_store.h" 

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_sett3 = NULL;
lv_obj_t * ui_bird3 = NULL;
lv_obj_t * ui_Panel = NULL;
lv_obj_t * ui_Paneln = NULL;
lv_obj_t * ui_Labeln = NULL;
lv_obj_t * ui_Name = NULL;
lv_obj_t * ui_speech = NULL;
lv_obj_t * ui_Labelsp = NULL;
lv_obj_t * ui_save = NULL;
lv_obj_t * ui_reload = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_ButtonReload = NULL;
lv_obj_t * ui_LabelReload = NULL;
lv_obj_t * ui_ButtonSaveN = NULL;
lv_obj_t * ui_LabelSaveN = NULL;
// event funtions
void ui_event_sett3(lv_event_t * e)
{
    ui_handle_settings_back_from_screen3(e);
}


void ui_event_ButtonReload(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        reload_app(e);
    }
}

void ui_event_ButtonSaveN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        save_name(e);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Screen3, &ui_img_night_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_Screen3, 70, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sett3 = lv_imgbtn_create(ui_Screen3);
    lv_imgbtn_set_src(ui_sett3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_sett_on_png, NULL);
    lv_imgbtn_set_src(ui_sett3, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_sett_on_png, NULL);
    lv_obj_set_width(ui_sett3, 67);
    lv_obj_set_height(ui_sett3, 66);
    lv_obj_set_x(ui_sett3, -365);
    lv_obj_set_y(ui_sett3, -205);
    lv_obj_set_align(ui_sett3, LV_ALIGN_CENTER);

    ui_bird3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_bird3, &ui_img_bird_png);
    lv_obj_set_width(ui_bird3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bird3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bird3, 342);
    lv_obj_set_y(ui_bird3, -187);
    lv_obj_set_align(ui_bird3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bird3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bird3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel, 450);
    lv_obj_set_height(ui_Panel, 101);
    lv_obj_set_x(ui_Panel, -150);
    lv_obj_set_y(ui_Panel, 0);
    lv_obj_set_align(ui_Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel, lv_color_hex(0x2D3334), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel, lv_color_hex(0xF3F0A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Paneln = lv_obj_create(ui_Panel);
    lv_obj_set_width(ui_Paneln, 140);
    lv_obj_set_height(ui_Paneln, 101);
    lv_obj_set_x(ui_Paneln, -153);
    lv_obj_set_y(ui_Paneln, 0);
    lv_obj_set_align(ui_Paneln, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Paneln, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Paneln, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Paneln, lv_color_hex(0x0F0E0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Paneln, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Paneln, lv_color_hex(0xF3F0A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Paneln, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Paneln, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labeln = lv_label_create(ui_Paneln);
    lv_obj_set_width(ui_Labeln, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labeln, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Labeln, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labeln, "Name");
    lv_obj_set_style_text_color(ui_Labeln, lv_color_hex(0xD0D3D3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labeln, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labeln, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Name = lv_label_create(ui_Panel);
    lv_obj_set_width(ui_Name, 256);
    lv_obj_set_height(ui_Name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Name, 62);
    lv_obj_set_y(ui_Name, 0);
    lv_obj_set_align(ui_Name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Name, "");

    /* NEW: если имя уже сохранено — подставляем его в ui_Name */
    const char *stored_name = user_name_get();
    if (stored_name && stored_name[0] != '\0') {
        lv_label_set_text(ui_Name, stored_name);
    }

    lv_obj_set_style_text_color(ui_Name, lv_color_hex(0xF3F0A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Name, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Name, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speech = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_speech, &ui_img_speech_png);
    lv_obj_set_width(ui_speech, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_speech, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_speech, 216);
    lv_obj_set_y(ui_speech, -97);
    lv_obj_set_align(ui_speech, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_speech, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_speech, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_speech, 1800);

    ui_Labelsp = lv_label_create(ui_speech);
    lv_obj_set_width(ui_Labelsp, 208);
    lv_obj_set_height(ui_Labelsp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelsp, 3);
    lv_obj_set_y(ui_Labelsp, 10);
    lv_obj_set_align(ui_Labelsp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelsp, "What's your name, dear friend?");
    lv_obj_set_style_text_color(ui_Labelsp, lv_color_hex(0xF3F0A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelsp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Labelsp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelsp, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_save = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_save, &ui_img_save_png);
    lv_obj_set_width(ui_save, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_save, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_save, 366);
    lv_obj_set_y(ui_save, 169);
    lv_obj_set_align(ui_save, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_save, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_save, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_reload = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_reload, &ui_img_reload_png);
    lv_obj_set_width(ui_reload, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_reload, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_reload, -363);
    lv_obj_set_y(ui_reload, 171);
    lv_obj_set_align(ui_reload, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_reload, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_reload, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container1 = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_height(ui_Container1, 123);
    lv_obj_set_width(ui_Container1, lv_pct(100));
    lv_obj_set_x(ui_Container1, 1);
    lv_obj_set_y(ui_Container1, 172);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container1, 275, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonReload = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_ButtonReload, 238);
    lv_obj_set_height(ui_ButtonReload, 86);
    lv_obj_set_x(ui_ButtonReload, -144);
    lv_obj_set_y(ui_ButtonReload, 144);
    lv_obj_set_align(ui_ButtonReload, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonReload, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonReload, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonReload, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonReload, lv_color_hex(0x2D3334), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonReload, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ButtonReload, lv_color_hex(0xF3F0A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonReload, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonReload, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ButtonReload, lv_color_hex(0x3A4244), LV_PART_MAIN | LV_STATE_PRESSED);
lv_obj_set_style_border_width(ui_ButtonReload, 4, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelReload = lv_label_create(ui_ButtonReload);
    lv_obj_set_width(ui_LabelReload, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelReload, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelReload, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelReload, "Reload the app");
    lv_obj_set_style_text_color(ui_LabelReload, lv_color_hex(0xF3F0A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelReload, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelReload, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSaveN = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_ButtonSaveN, 143);
    lv_obj_set_height(ui_ButtonSaveN, 86);
    lv_obj_set_x(ui_ButtonSaveN, 216);
    lv_obj_set_y(ui_ButtonSaveN, 141);
    lv_obj_set_align(ui_ButtonSaveN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonSaveN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonSaveN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonSaveN, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonSaveN, lv_color_hex(0x2D3334), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonSaveN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ButtonSaveN, lv_color_hex(0xF3F0A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonSaveN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonSaveN, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

     lv_obj_set_style_bg_color(ui_ButtonSaveN, lv_color_hex(0x3A4244), LV_PART_MAIN | LV_STATE_PRESSED);
lv_obj_set_style_border_width(ui_ButtonSaveN, 4, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelSaveN = lv_label_create(ui_ButtonSaveN);
    lv_obj_set_width(ui_LabelSaveN, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSaveN, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSaveN, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSaveN, "Save");
    lv_obj_set_style_text_color(ui_LabelSaveN, lv_color_hex(0xF3F0A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSaveN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSaveN, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_sett3, ui_event_sett3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonReload, ui_event_ButtonReload, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSaveN, ui_event_ButtonSaveN, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_sett3 = NULL;
    ui_bird3 = NULL;
    ui_Panel = NULL;
    ui_Paneln = NULL;
    ui_Labeln = NULL;
    ui_Name = NULL;
    ui_speech = NULL;
    ui_Labelsp = NULL;
    ui_save = NULL;
    ui_reload = NULL;
    ui_Container1 = NULL;
    ui_ButtonReload = NULL;
    ui_LabelReload = NULL;
    ui_ButtonSaveN = NULL;
    ui_LabelSaveN = NULL;
}
