// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sixteen_str

#include "ui.h"
#include "ui_events.h"      
#include "builtin_texts.h"  

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Img = NULL;
lv_obj_t * ui_ContainerQ = NULL;
lv_obj_t * ui_PanelQ = NULL;
lv_obj_t * ui_LabelQ = NULL;
lv_obj_t * ui_ContainerB = NULL;
lv_obj_t * ui_choice1 = NULL;
lv_obj_t * ui_LabelCh1 = NULL;
lv_obj_t * ui_choice2 = NULL;
lv_obj_t * ui_LabelCh2 = NULL;
lv_obj_t * ui_end = NULL;
lv_obj_t * ui_LabelEnd = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_Image7 = NULL;
// event funtions
void ui_event_choice1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        button_choose_1(e);
    }
}

void ui_event_choice2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        button_choose_2(e);
    }
}

void ui_event_end(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        button_choose_end(e);
    }
}

void ui_event_btnchg(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        on_btn_change_pressed(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Screen1, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Screen1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Screen1, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Screen1, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Img = lv_img_create(ui_Screen1);
    lv_obj_set_width(ui_Img, 450);
    lv_obj_set_height(ui_Img, 276);
    lv_obj_set_x(ui_Img, -3);
    lv_obj_set_y(ui_Img, -91);
    lv_obj_set_align(ui_Img, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Img, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Img, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Img, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Img, lv_color_hex(0xF3F0A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Img, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Img, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerQ = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_ContainerQ);
    lv_obj_set_width(ui_ContainerQ, 374);
    lv_obj_set_height(ui_ContainerQ, 57);
    lv_obj_set_x(ui_ContainerQ, 23);
    lv_obj_set_y(ui_ContainerQ, 4);
    lv_obj_set_align(ui_ContainerQ, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerQ, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContainerQ, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerQ, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    

    ui_PanelQ = lv_obj_create(ui_ContainerQ);
    lv_obj_set_width(ui_PanelQ, 352);
    lv_obj_set_height(ui_PanelQ, 54);
    lv_obj_set_x(ui_PanelQ, 4);
    lv_obj_set_y(ui_PanelQ, -1);
    lv_obj_set_align(ui_PanelQ, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelQ, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelQ, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelQ, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
     lv_obj_set_style_radius(ui_PanelQ, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelQ = lv_label_create(ui_PanelQ);
    lv_obj_set_width(ui_LabelQ, 357);
    lv_obj_set_height(ui_LabelQ, 29);
    lv_obj_set_align(ui_LabelQ, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelQ, "");
    lv_obj_set_style_text_color(ui_LabelQ, lv_color_hex(0xF3F0A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelQ, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelQ, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelQ, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerB = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_ContainerB);
    lv_obj_set_width(ui_ContainerB, 821);
    lv_obj_set_height(ui_ContainerB, 93);
    lv_obj_set_x(ui_ContainerB, 6);
    lv_obj_set_y(ui_ContainerB, -22);
    lv_obj_set_align(ui_ContainerB, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerB, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContainerB, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerB, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_ContainerB, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContainerB, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContainerB, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContainerB, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ContainerB, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ContainerB, 305, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_choice1 = lv_btn_create(ui_ContainerB);
    lv_obj_set_width(ui_choice1, 255);
    lv_obj_set_height(ui_choice1, 95);
    lv_obj_set_x(ui_choice1, -303);
    lv_obj_set_y(ui_choice1, 193);
    lv_obj_set_align(ui_choice1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_choice1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_choice1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_choice1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_choice1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_choice1, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_choice1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_choice1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    

    ui_LabelCh1 = lv_label_create(ui_choice1);
    lv_obj_set_width(ui_LabelCh1, 228);
    lv_obj_set_height(ui_LabelCh1, LV_SIZE_CONTENT); 
    lv_obj_set_x(ui_LabelCh1, 22);
    lv_obj_set_y(ui_LabelCh1, 23);
    lv_obj_set_align(ui_LabelCh1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCh1, "");
    lv_obj_set_style_text_color(ui_LabelCh1, lv_color_hex(0xF3F0A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCh1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelCh1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCh1, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_choice2 = lv_btn_create(ui_ContainerB);
    lv_obj_set_width(ui_choice2, 255);
    lv_obj_set_height(ui_choice2, 95);
    lv_obj_set_x(ui_choice2, -158);
    lv_obj_set_y(ui_choice2, 14);
    lv_obj_set_align(ui_choice2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_choice2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_choice2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_choice2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_choice2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_choice2, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_choice2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_choice2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCh2 = lv_label_create(ui_choice2);
    lv_obj_set_width(ui_LabelCh2, 228);
    lv_obj_set_height(ui_LabelCh2, LV_SIZE_CONTENT); 
    lv_obj_set_x(ui_LabelCh2, 4);
    lv_obj_set_y(ui_LabelCh2, 7);
    lv_obj_set_align(ui_LabelCh2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCh2, "");
    lv_obj_set_style_text_color(ui_LabelCh2, lv_color_hex(0xF3F0A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCh2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelCh2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCh2, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_end = lv_btn_create(ui_ContainerB);
    lv_obj_set_width(ui_end, 403);
    lv_obj_set_height(ui_end, 56);
    lv_obj_set_x(ui_end, 0);
    lv_obj_set_y(ui_end, -22);
    lv_obj_set_align(ui_end, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_end, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_IGNORE_LAYOUT | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_end, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_end, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_end, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
     lv_obj_set_style_radius(ui_end, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEnd = lv_label_create(ui_end);
    lv_obj_set_width(ui_LabelEnd, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEnd, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelEnd, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEnd, "It was a wonderful story! Try Again.");
    lv_obj_set_style_text_color(ui_LabelEnd, lv_color_hex(0xF3F0A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelEnd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelEnd, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image6, &ui_img_arrow_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image6, -192);
    lv_obj_set_y(ui_Image6, 119);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image6, 1400);

    ui_Image7 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image7, &ui_img_arrow_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image7, 191);
    lv_obj_set_y(ui_Image7, 118);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image7, 450);

    lv_obj_add_event_cb(ui_choice1, ui_event_choice1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_choice2, ui_event_choice2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_end, ui_event_end, LV_EVENT_ALL, NULL);

    ui_story_start();
}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Img = NULL;
    ui_ContainerQ = NULL;
    ui_PanelQ = NULL;
    ui_LabelQ = NULL;
    ui_ContainerB = NULL;
    ui_choice1 = NULL;
    ui_LabelCh1 = NULL;
    ui_choice2 = NULL;
    ui_LabelCh2 = NULL;
    ui_end = NULL;
    ui_LabelEnd = NULL;
    ui_Image6 = NULL;
    ui_Image7 = NULL;

}
