// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project_1

#include "ui.h"


// IMAGE DATA: assets/D13_l.png
lv_img_dsc_t ui_img_d13_l_png = {
    .header.always_zero = 0,
    .header.w = 529,
    .header.h = 314,
    .header.cf = LV_IMG_CF_TRUE_COLOR,
};

void ui_img_d13_l_png_load()
{
    ui_img_d13_l_png.data = UI_LOAD_IMAGE("S:assets_l/ui_img_d13_l_png.bin", 332212);
    ui_img_d13_l_png.data_size = 332212;
}
