// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: album

#include "ui.h"


// IMAGE DATA: assets/B2_2_s.png
lv_img_dsc_t ui_img_b2_2_s_png = {
    .header.always_zero = 0,
    .header.w = 458,
    .header.h = 263,
    .header.cf = LV_IMG_CF_TRUE_COLOR,
};

void ui_img_b2_2_s_png_load()
{
    ui_img_b2_2_s_png.data = UI_LOAD_IMAGE("S:assets_s/ui_img_b2_2_s_png.bin", 240908);
    ui_img_b2_2_s_png.data_size = 240908;
}
