// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sixteen_str

#include "ui.h"


// IMAGE DATA: assets/bird.png
lv_img_dsc_t ui_img_bird_png = {
    .header.always_zero = 0,
    .header.w = 80,
    .header.h = 93,
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
};

void ui_img_bird_png_load()
{
    ui_img_bird_png.data = UI_LOAD_IMAGE("S:assets/ui_img_bird_png.bin", 22320);
    ui_img_bird_png.data_size = 22320;
}
