// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sixteen_str

#include "ui.h"


// IMAGE DATA: assets/sett_off.png
lv_img_dsc_t ui_img_sett_off_png = {
    .header.always_zero = 0,
    .header.w = 65,
    .header.h = 65,
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
};

void ui_img_sett_off_png_load()
{
    ui_img_sett_off_png.data = UI_LOAD_IMAGE("S:assets/ui_img_sett_off_png.bin", 12675);
    ui_img_sett_off_png.data_size = 12675;
}
