// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sixteen_str

#include "ui.h"


// IMAGE DATA: assets/question.png
lv_img_dsc_t ui_img_question_png = {
    .header.always_zero = 0,
    .header.w = 350,
    .header.h = 120,
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
};

void ui_img_question_png_load()
{
    ui_img_question_png.data = UI_LOAD_IMAGE("S:assets/ui_img_question_png.bin", 126000);
    ui_img_question_png.data_size = 126000;
}
