// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: sixteen_str

#include "ui.h"


// IMAGE DATA: assets/frame_lrg.png
lv_img_dsc_t ui_img_frame_lrg_png = {
    .header.always_zero = 0,
    .header.w = 615,
    .header.h = 420,
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
};

void ui_img_frame_lrg_png_load()
{
    ui_img_frame_lrg_png.data = UI_LOAD_IMAGE("S:assets/ui_img_frame_lrg_png.bin", 774900);
    ui_img_frame_lrg_png.data_size = 774900;
}
